name: Run Step

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 开始
        run: |
          git clone ${{ secrets.REPO }}
          mv mimotion/manual.py manual.py
          rm mimotion
          pip3 install requests
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}'
          python3 manual.py ${user} ${passwd}
